secretsapp/urls.py
from django.urls import path, include
from django.contrib import admin
from secretsmodules import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path('secretsmodules/', include('secretsmodules.urls')),
    # path('admin/', admin.site.urls),
    path('', views.HomePageView.as_view(), name='index'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.LoginForm.as_view(), name='login'),
    path('', include('secretsmodules.urls')),
]
#if settings.DEBUG is True:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secretsmodules/urls.py
# howdy/urls.py
from django.urls import path
from django.urls import re_path
from secretsmodules import views
app_name = 'secretsmodules'

urlpatterns = [
    re_path(r'^details/(?P<pk>\d{1,50})/$', views.DetailsView.as_view(), name='details'),
    re_path(r'^add_to_cart/(?P<secret_id>[0-9]+)$', views.add_to_cart, name='add_to_cart'),
    re_path(r'^remove_from_cart/(?P<secret_id>[0-9]+)$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^register/$', views.RegisterForm.as_view(), name='register'),
    path('cart/', views.get_cart, name='cart'),
    path('user_secrets/', views.get_user_secrets, name='user_secrets'),
    re_path(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    path('profile/', views.EditProfile.as_view(), name='profile'),
]

secretsmodules/models.py
from django.db import models
from django.contrib.auth.models import User
from decimal import Decimal
# Create your models here.

class Country(models.Model):

    name = models.CharField(max_length = 150, unique = True)
    code = models.CharField(max_length = 2, unique = True)


class Secret(models.Model):

    title = models.CharField(max_length = 264, unique = False)
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=10)
    picture = models.ImageField(upload_to = 'secret_pics',blank = True)
    date = models.DateField()
    country_of_origin = models.ForeignKey('Country',on_delete=models.PROTECT)
    rank = models.IntegerField()


class UserProfile(models.Model):
    #username, password, first and last name and email are included in djangos user class

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = 'profile')
    address = models.CharField(max_length = 264, unique = False, blank = True)
    phone = models.CharField(max_length = 20,  blank = True)
    balance = models.DecimalField(max_digits=20,decimal_places=2,default=Decimal('10000.00'))


class Cart(models.Model):

    user = models.ForeignKey('UserProfile', on_delete=models.PROTECT)
    purchase_date = models.DateTimeField( auto_now_add = True)


class PurchasedItem(models.Model):

    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    secret = models.ForeignKey('Secret', on_delete=models.CASCADE)
    purchased_price = models.DecimalField(decimal_places=2, max_digits=10)

secretsmodules/forms.py
from django import forms
from django.core import validators
from django.contrib.auth import get_user_model
from . import models

class UserForm(forms.Form):
    username = forms.CharField(widget = forms.TextInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g johndoe',
            'pattern': '[A-Za-z0-9_]{3,20}',
            'title': 'alphanumeric symbols or underscore between 3 and 20 characters'
        })
    )
    first_name = forms.CharField(widget = forms.TextInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. John',
            'pattern': '([^\s][A-zÀ-ž\s]+)',
            'title': 'Alphabet symbols and spaces only'
        }))
    last_name = forms.CharField(widget = forms.TextInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. Doe',
            'pattern': '([^\s][A-zÀ-ž\s]+)',
            'title': 'Alphabet symbols and spaces only'
        }))
    email = forms.EmailField(widget = forms.EmailInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. johndoe@gmail.com',
        }))
    email_repeat = forms.EmailField(widget = forms.EmailInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. johndoe@gmail.com',
        }))
    password = forms.CharField(widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
    }))
    password_repeat = forms.CharField(widget = forms.PasswordInput(attrs = {
        'class' : 'form-control',
    }))
    address = forms.CharField(max_length = 264, required = False, widget = forms.TextInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. Embassy of Ecuador, London',
        }))
    phone = forms.CharField(max_length = 20, required = False, widget = forms.TextInput(
        attrs = {
            'class' : 'form-control',
            'placeholder' : 'e.g. 555 555 555 555',
        }))
    botcatcher = forms.CharField(required = False, widget = forms.HiddenInput)  #this is to catch bots: hidden field, so actual user won't fill it, bot will

    def clean(self):
        clean_data = super().clean()
        botcatcher = clean_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("Bot caught")
        if clean_data['email']!=clean_data['email_repeat']:
            raise forms.ValidationError("Emails don't match")
        if clean_data['password']!=clean_data['password_repeat']:
            raise forms.ValidationError("Passwords don't match")

    # def clean_botcatcher(self):  #custom validator
    #     botcatcher = self.cleaned_data['botcatcher']
    #     if len(botcatcher) > 0:
    #         raise forms.ValidationError("Bot caught")
    #     return botcatcher


class UserEditForm(forms.ModelForm):

    class Meta():
        fields = ('first_name','last_name')
        model = get_user_model()
        widgets = {

                'first_name' : forms.TextInput(
                        attrs = {
                            'class' : 'form-control',
                            'placeholder' : 'e.g. John',
                            'pattern': '([^\s][A-zÀ-ž\s]+)',
                            'title': 'Alphabet symbols and spaces only'
                        }),
                'last_name' : forms.TextInput(
                        attrs = {
                            'class' : 'form-control',
                            'placeholder' : 'e.g. Doe',
                            'pattern': '([^\s][A-zÀ-ž\s]+)',
                            'title': 'Alphabet symbols and spaces only'
                        }),                
        }


class ProfileEditForm(forms.ModelForm):
    class Meta():
        model = models.UserProfile
        fields =  ('phone','address')
        widgets = {
            'phone': forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'e.g. 555 555 555 555',
                }),
            'address' : forms.TextInput(
                attrs = {
                    'class' : 'form-control',
                    'placeholder' : 'e.g. Embassy of Ecuador, London',
                }),

        }

secretsmodules/views.py
import json
import datetime
from decimal import *
from operator import itemgetter
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from django.http import HttpResponse, HttpResponseRedirect
from . import forms
from . import models
from django.core import serializers
from secretsmodules.models import Secret, UserProfile, PurchasedItem, Cart
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout, get_user_model
import urllib
from django.conf import settings
from django.contrib import messages

# Create your views here.


def duplicate_mail(email):
    users = list(User.objects.filter(email = email))
    if len(users) > 0:
        return True
    return False

class HomePageView(ListView):
    template_name = 'secretsmodules/index.html'
    context_object_name = 'all_secrets'  #default: objectname_list
    ordering = ['-date']
    model = models.Secret

class DetailsView(DetailView):
    model = models.Secret
    template_name = 'secretsmodules/details.html'
    context_object_name = 'secret'    #default: objectname.

@login_required
def get_cart(request):
    cart = request.session.get('cart', dict())
    return render(request, 'secretsmodules/cart.html')

@login_required
def get_user_secrets(request):
    profile = UserProfile.objects.get(user=request.user)
    print(profile)
    purchased_items = Cart.objects.filter(user_id=profile.pk).values()
    user_purchased = list()
    # group by basket
    for value in purchased_items:
        item = PurchasedItem.objects.get(cart_id=value['id']).__dict__
        secret_dict = {"secret": Secret.objects.filter(pk=item['secret_id']).values()[0],
                       "purchase_date": value['purchase_date'], "pk": item['secret_id']}
        user_purchased.append(secret_dict)

    # sort by latest key
    user_purchased.sort(key=itemgetter('purchase_date'), reverse=True)
    return render(request, 'secretsmodules/user_secrets.html', context={'user_purchased': user_purchased})

@login_required
def add_to_cart(request, secret_id):
    if request.user.is_authenticated:
        cart = request.session.get('cart', dict())
        secret = Secret.objects.filter(pk=secret_id).values()[0]
        # if item already in cart
        if secret_id in cart:
            cart[secret_id]['quantity'] = cart[secret_id]['quantity'] + 1
        else:
            cart[secret_id] = {"secret": secret['title'], "quantity": 1, "price": float(secret['price'])}
        request.session['cart'] = cart
        return redirect('/cart')
    else:
        return HttpResponseRedirect(reverse('login'))

@login_required
def remove_from_cart(request, secret_id):
    cart = request.session.get('cart', dict())
    cart.pop(secret_id, None)
    request.session['cart'] = cart
    return redirect('/cart')

class CheckoutView(LoginRequiredMixin,TemplateView):
    def get(self, request, **kwargs):
        cart = request.session.get('cart', dict())
        total_order = 0
        profile = UserProfile.objects.get(user=request.user)
        balance = profile.balance
        for key in cart:
            total_order = total_order + (cart[key]['price'])
        return render(request, 'secretsmodules/checkout.html', context={"total_order": total_order, "balance": balance})
    def post(self, request, **kwargs):
        cart = request.session.get('cart')
        profile = UserProfile.objects.get(user=request.user)
        for key in cart:
            item_price = cart[key]['price']
            balance = float(profile.balance) - item_price
            if balance < 0:
                return
            else:
                secret = Secret.objects.get(pk=key)
                cart_item = Cart(user=profile, purchase_date=datetime.datetime.now())
                cart_item.save()
                purchased_item = PurchasedItem(cart=cart_item, secret=secret, purchased_price=item_price)
                purchased_item.save()
                profile.balance = Decimal(balance)
                profile.save()
        request.session['cart'] = dict()
        return render(request, 'secretsmodules/checkout_finished.html', context={"current_balance": profile.balance})




class RegisterForm(TemplateView):
    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        form = forms.UserForm()
        return render(request, 'secretsmodules/register.html', context={'form': form})
    def post(self, request, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        form = forms.UserForm(request.POST)
        if form.is_valid():

            data = form.cleaned_data
            try:
                if duplicate_mail(data['email']):
                    form.add_error(field = 'email', error = "Email already in user")
                try:
                    validate_password(data['password'])
                except ValidationError as ve:
                    form.add_error(field = 'password', error = ve.messages)
                if len(form.errors) > 0:
                    return render(request, 'secretsmodules/register.html', context={'form': form})
                user = User.objects.create_user(username=data['username'],
                                             email=data['email'],
                                             password=data['password'],
                                             first_name = data['first_name'],
                                             last_name = data['last_name'])

            except IntegrityError as e:

                if 'unique constraint' in str(e).lower():
                    form.add_error(field = 'username', error="Username already in use")
                else:
                    form.add_error(field = none, error = "Unspecified error, try again later")
                return render(request, 'secretsmodules/register.html', context={'form': form})
            except Exception as e:
                form.add_error(field = None, error = "Unspecified Integrity error, try again later" )
                return render(request, 'secretsmodules/register.html', context={'form': form})
            try:
                profile = UserProfile(user = user, address = data['address'], phone = data['phone'], balance = 0)
                profile.save()
            except Exception as ex:
                print(ex)
            if profile.pk is None:
                user.delete()
                form.add_error(field = None, error = "Error registering, try again later." )
                return render(request, 'secretsmodules/register.html', context={'form': form})


            login(request=request,user=user)
            return HttpResponseRedirect(reverse('index'))   #change later to profile page
        else:
            return render(request, 'secretsmodules/register.html', context={'form': form})


class LoginForm(TemplateView):
    def get(self, request, **kwargs):
        if request.user.is_authenticated:
            return redirect('/')
        return render(request, 'secretsmodules/login.html')
    def post(self, request, **kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')
        botcarcher = request.POST.get('bctch')
        if len(botcarcher) > 0:
            return HttpResponse('Bot caught!') #here we must implement captcha
        failed_attemts = request.session.get("FailedLogin", 0)
        if failed_attemts >=3:
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req =  urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            ''' End reCAPTCHA validation '''

            if result['success']:
                request.session["FailedLogin"] = 0
            elif failed_attemts == 3:
                request.session["FailedLogin"] +=1
                return render(request, 'secretsmodules/login.html', context={'captcha': True, "error":"user not found"})
            else:
                request.session["FailedLogin"] +=1
                return render(request, 'secretsmodules/login.html', context={'captcha': True, "error":"captcha validation failed"})
        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request=request, user=user)

                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('User not active')
        else:
            if failed_attemts == 0:
                request.session["FailedLogin"] = 1
                return render(request, 'secretsmodules/login.html', context={"error":"user not found"})
            else:
                request.session["FailedLogin"] +=1
                return render(request, 'secretsmodules/login.html', context={"error":"user not found"})
            return HttpResponse('invalid login details')

class EditProfile(LoginRequiredMixin, TemplateView):
    def get(self, request, **kwargs):

        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileEditForm(instance = request.user.profile)

templates/secretsmodules/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"\>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}"\>
        <meta charset="utf-8">
        <title>Howdy!</title>
        <script src='https://www.google.com/recaptcha/api.js'></script>
    </head>
    <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container">
    <a class="navbar-brand" href="/">Secret Shop</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link" href="/"> <i>Secrets </i></a>
        </li>

      </ul>
      <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="/cart">MyCart ({{request.session.cart.items|length}})</a>
        </li>
         <li class="nav-item">
            <a class="nav-link" href="/user_secrets">MySecrets</a>
        </li>
        <li class="nav-item">
           <a class="nav-link" href="/profile">Edit Profile</a>
       </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'secretsmodules:register' %}">Register</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
      </ul>
    </div>
    </div>
  </nav>

</div>
      </nav>
        <!-- <div class="card text-center">
            <div class="card-header">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link" href="/"> <i>Secrets </i></a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="/cart">MyCart</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'secretsmodules:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div> -->
        <div class="card-body">
            <div class="container">
                {% block content %}
                {% endblock %}
            </div>
        </div>
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    </body>

templates/secretsmodules/cart.html
{% extends 'secretsmodules/base.html' %}
{% block content %}
<div>
   <h1> Cart details </h1>
      {% if not request.session.cart %}
        <h6> Your cart is empty </h6>
        <a class="btn btn-secondary" href="/"> KEEP SHOPPING </a>
    {% else %}
   <div class="btn-group" role="group" aria-label="Basic example">
      <a class="btn btn-primary" href="/checkout"> CHECKOUT NOW </a>
      <a class="btn btn-secondary" href="/"> KEEP SHOPPING </a>
   </div>
   <div class="container">
      <div class="row">
         <table class="table  table-striped">
            <thead>
               <tr>
                  <th scope="col">Secret Title</th>
                  <th scope="col">Secret Price</th>
                  <th scope="col">Remove</th>
               </tr>
            </thead>

             <tbody>
               {% for key, value in request.session.cart.items %}
               <tr>
                  <td>
                     {{ value.secret}}
                  </td>

                  <td> {{value.price}}</td>

                  <td> <a class="btn btn-warning" href="{% url 'secretsmodules:remove_from_cart' secret_id=key %}">Remove</a></td>
               </tr>
               {% endfor %}
            </tbody>
         </table>
      </div>
   </div>
</div>
{% endif %}
{% endblock %}

templates/secretsmodules/checkout.html
{% extends 'secretsmodules/base.html' %}
{% block content %}
<div>
   <h1>Checkout </h1>
    <div class="jumbotron">
        <h4>Total Price: $ {{ total_order }}</h4>
        <h6> Your balance: $ {{ balance }}  </h6>
        {% if balance > total_order %}
        <form class="" action="" method="post">
            {% csrf_token %}
            <input type="submit" class='btn btn-primary' value="Pay now">
            <a href="/"> keep shopping </a>
        </form>
        {% elif balance < total_order %}
        <h6> Insufficent balance </h6>
    </div>
{% endif %}
{% endblock %}

templates/secretsmodules/checkout_finished.html
{% extends 'secretsmodules/base.html' %}
{% block content %}
<div>
   <h1>Thank you for your order! </h1>
   <div class="jumbotron">
      <h6> Your remaining balance is {{current_balance}} </h6>
      <a class='btn btn-primary' href="/"> Keep shopping </a>
   </div>
</div>
{% endblock %}

templates/secretsmodules/details.html
{% extends "secretsmodules/base.html" %}
{% load static %}
  {% block content %}
    <div class="jumbotron">

        <h2>  {{secret.title}}</h2>
        {% if secret.picture %}
        <img src="{{ secret.picture.url }}" alt="Error" >
        {% else %}
        <img src="{% static 'images/sandman.jpg' %}" >
        {% endif %}
        <div class="">

            <p>
              {{secret.description}}
            </p>
            <p>
                Date: {{secret.date | date:"Y-m-d"}}
            </p>
            <p>
            Country: {{secret.country_of_origin.name}}</p>
            <p>
            Price: {{secret.price}} $
            </p>
            <p>
            Rank: {{secret.rank}}
          </p>

        </div>

    </div>
  {% endblock %}

templates/secretsmodules/index.html
{% extends "secretsmodules/base.html" %}
{% load static %}
{% block content %}
<div class="row">
    {% if all_secrets %}
    {% for secret in all_secrets %}
    <div class="col-4 secret-entry">
        <h4>
            {{secret.title}}
        </h4>
        <div class="" style="min-height: 150px">
            {{secret.description}}
        </div>
        <div class="entry-img">
          {% if secret.picture %}
          <img src="{{ secret.picture.url }}" alt="Error">
          {% else %}
          <img src="{% static 'images/sandman.jpg' %}">
          {% endif %}
        </div>

        <br>
        <a class="btn btn-success" href="{% url 'secretsmodules:add_to_cart' secret_id=secret.id %}">Add item</a>
        Buy  {{secret.price }} $
        </a>
        <a class="detail_button btn btn-primary" href="{% url 'secretsmodules:details' secret.id %}">
        Details
        </a>
    </div>
    {% endfor %}
</div>
{% else %}
<h3>No Secrets Found</h3>
{% endif %}
</div>
{% endblock %}

templates/secretsmodules/login.html
{% extends "secretsmodules/base.html" %}
  {% block content %}


    <div class="jumbotron">
      <form action="" method="post">
          {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger text-center">
            {{ error }} {{ request.session.LoginFailed }}
        </div>
        {% endif %}

        <div class="form-group row">
          <label for="username" class="col-sm-2 col-form-label">Username</label>
          <div class="col-sm-10">
            <input type="text" name="username" value="" class="form-control" required>
          </div>
        </div>
        <div class="form-group row">
          <label for="password" class="col-sm-2 col-form-label">Password</label>
          <div class="col-sm-10">
            <input type="password" name="password" class="form-control" id="password" placeholder="Password">
          </div>
            <input type="hidden" name = "bctch">
        </div>
        {% if captcha %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label">Prove you're human</label>
          <div class="col-sm-10">
            <div class="g-recaptcha" data-sitekey="6LdnVVwUAAAAADTpG9rKVlKsOnErKFyMwqbPAEvp"></div>
          </div>
        </div>

        {% endif %}

        <div class="form-group row">
          <div class="offset-sm-2 col-sm-10">
            <button type="submit" class="btn btn-primary">Sign in</button>
          </div>
        </div>
      </form>

    </div>

  {% endblock %}

templates/secretsmodules/profile.html
{% extends "secretsmodules/base.html" %}

{% block content %}
<div class="container">
  <h1>Edit Profile</h1>

  {% if success %}
      <div class="alert alert-success">
        Profile Updated Sucessfully
      </div>
  {% endif %}

  <form class="{% url 'secretsmodules:profile'}" method="post">
      {% csrf_token %}
      <p>
        <label>
          Username:
        </label>
        <input class= "form-control" disabled readonly value="{{user.username}}" >
      </p>
    <p>
      <label>
        Email:
      </label>
      <input class= "form-control" disabled readonly value="{{user.email}}" >
    </p>

      {{ user_form.as_p }}
      {{profile_form.as_p}}
      <p>
        <label>
          Balance:
        </label>
        <input class= "form-control" disabled readonly value="{{user.profile.balance}} $" >
      </p>


      <input type="submit" name="" value="Update" class="btn btn-primary">
  </form>
</div>

{% endblock content %}

templates/secretsmodules/register.html
{% extends "secretsmodules/base.html" %}
  {% block content %}
        <h1>Register</h1>
        <form class="" action="" method="post">
          {{form.non_field_errors}}
            {# {{form.as_p}} #}
            {% for field in form %}

            {% if field.name == "botcatcher" %}
                  {{ field }}
            {% else %}
            <div class="form-group row">

                <label class="col-sm-2 col-form-label" for="{{ field.name }}">{{ field.label }}</label>
                <div class="col-sm-10">
                    {{ field }}
                    {{ field.errors}}
                </div>
            </div>
            {% endif %}

              {% endfor %}
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Register">
        </form>
  {% endblock %}

templates/secretsmodules/user_secrets.html
{% extends 'secretsmodules/base.html' %}
{% block content %}
<div>
   <h1> Your secrets </h1>
   <div class="jumbotron">

      {% for key in user_purchased %}
      <div class="card">
         <div class="card-body">
            <h6>
             <span>{{key.purchase_date}}</span>
              <button class='btn btn-primary pull-right'  data-toggle="collapse" data-target="#collapseExample{{key.pk}}" aria-expanded="false" aria-controls="collapseExample">See more</button>
            </h6>

            <div class="collapse" id="collapseExample{{key.pk}}">
            <h5 class="card-title"> {{ key.secret.title}} </h5>
            <h6 class="card-subtitle mb-2 text-muted"> {{ key.secret.price}}</h6>
         </div>
      </div>
      {% endfor %}
         <a class='btn btn-primary' href="/"> Keep shopping </a>
   </div>
</div>
{% endblock %}